include classpath("application.conf")

queues {
  booking-created-dlq {}
  booking-created {
    defaultVisibilityTimeout = 30 seconds
    deadLettersQueue {
      name = "booking-created-dlq"
      maxReceiveCount = 3
    }
  }
}
